

##### Download the file "fake reviews dataset.csv" from the link provided.

##### Dataset download link : https://osf.io/tyue9/

### Instructions to run the code:

##### 1) To view stemming results, only run stemming cell from data preprocessing and then run the following cells.
##### 2) To view lemmatization results, only run lemmatization cell from data preprocessing and then run the following cells.
##### 3) For combining results of Stemming and Countervectorizer, do not run TF-IDF cell.
##### 4) For combining results of Stemming and TF-IDF cell, do not run Countervectorizer cell.
##### 5) For combining results of Lemmatization and TF-IDF cell, do not run Countervectorizer cell.
##### 6) For combining results of Lemmatization and Countervectorizer cell, do not run TF-IDF cell.
##### 7) Before executing any model, first run any preprocessing technique(Stemming & Lemmatization) and feature extraction cell(Countvectorizer & TF-IDF) respectively.

##### 8) The displayed results are of lemmatization and TF-IDF on every classifier.

##Importing libraries

In [34]:
# import these modules
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt
from nltk.corpus import stopwords
import re
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer
import nltk
from sklearn.metrics import classification_report
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics
import numpy as np
import itertools
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import LinearSVC
import numpy as np
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import AdaBoostClassifier,RandomForestClassifier
from xgboost import XGBClassifier

In [35]:


nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Package abc is already up-to-date!
[nltk_data]    | Downloading package alpino to /root/nltk_data...
[nltk_data]    |   Package alpino is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_ru is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package basque_grammars is already up-to-date!
[nltk_data]    | Downloading package biocreative_ppi to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Pac

True

##Data Pre-processing

In [3]:

df = pd.read_csv("fake reviews dataset.csv")
df


category  rating label  \
0                Home_and_Kitchen_5     5.0    CG   
1                Home_and_Kitchen_5     5.0    CG   
2                Home_and_Kitchen_5     5.0    CG   
3                Home_and_Kitchen_5     1.0    CG   
4                Home_and_Kitchen_5     5.0    CG   
...                             ...     ...   ...   
40427  Clothing_Shoes_and_Jewelry_5     4.0    OR   
40428  Clothing_Shoes_and_Jewelry_5     5.0    CG   
40429  Clothing_Shoes_and_Jewelry_5     2.0    OR   
40430  Clothing_Shoes_and_Jewelry_5     1.0    CG   
40431  Clothing_Shoes_and_Jewelry_5     5.0    OR   

                                                   text_  
0      Love this!  Well made, sturdy, and very comfor...  
1      love it, a great upgrade from the original.  I...  
2      This pillow saved my back. I love the look and...  
3      Missing information on how to use it, but it i...  
4      Very nice set. Good quality. We have had the s...  
...                                                  ...  
40427  I had read some reviews saying that this bra r...  
40428  I wasn't sure exactly what it would be. It is ...  
40429  You can wear the hood by itself, wear it with ...  
40430  I liked nothing about this dress. The only rea...  
40431  I work in the wedding industry and have to wor...  

[40432 rows x 4 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40432 entries, 0 to 40431
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   category  40432 non-null  object 
 1   rating    40432 non-null  float64
 2   label     40432 non-null  object 
 3   text_     40432 non-null  object 
dtypes: float64(1), object(3)
memory usage: 1.2+ MB


In [5]:
df.isnull().sum()

category    0
rating      0
label       0
text_       0
dtype: int64

In [6]:
df.shape

(40432, 4)

In [7]:
df['label'].value_counts()

CG    20216
OR    20216
Name: label, dtype: int64

In [8]:
df.rename(columns = {'text_':'review_text'}, inplace = True)

In [9]:
df = df.replace({'label': {'CG': 1, 'OR': 0}})

In [10]:
text = df['review_text'].copy()

##Stemming

In [ ]:
lemmatizer = WordNetLemmatizer()
ps = PorterStemmer()
corpus = []
for i in range(0, len(text)):
    review = re.sub('[^a-zA-Z]', ' ', text[i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

##Lemmatization

In [12]:
lemmatizer = WordNetLemmatizer()
ps = PorterStemmer()
corpus = []
for i in range(0, len(text)):
    review = re.sub('[^a-zA-Z]', ' ', text[i])
    review = review.lower()
    review = review.split()
    
    review = [lemmatizer.lemmatize(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

## CounterVectorizer

In [ ]:
## Applying Countvectorizer
# ngram_range=(1,3)
# Creating the Bag of Words model

cv = CountVectorizer(max_features=10000, ngram_range=(1,3))
X = cv.fit_transform(corpus).toarray()

In [ ]:
X.shape

(40432, 10000)

In [ ]:
y = df['label']

##TF-IDF Vectorizer

In [14]:
## Applying Countvectorizer
# Creating the Bag of Words model
from sklearn.feature_extraction.text import TfidfVectorizer
cv = TfidfVectorizer(max_features=10000,ngram_range=(1,3))
X = cv.fit_transform(corpus).toarray()

In [15]:
y = df['label']

## Train-Test Split

In [ ]:
## Divide the dataset into Train and Test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=0)

In [ ]:
cv.get_feature_names()[:20]

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['aa',
 'aa batteri',
 'aaa',
 'ab',
 'abandon',
 'abil',
 'abl',
 'abl find',
 'abl get',
 'abl go',
 'abl make',
 'abl put',
 'abl read',
 'abl see',
 'abl take',
 'abl use',
 'abl wear',
 'abrupt',
 'absolut',
 'absolut love']

##MultinomialNB

In [17]:

classifier=MultinomialNB()

classifier.fit(X_train, y_train)
pred = classifier.predict(X_test)
score = metrics.accuracy_score(y_test, pred)
print("accuracy:   %0.3f" % score)
cm = metrics.confusion_matrix(y_test, pred)

accuracy:   0.869


In [20]:
classifier=MultinomialNB(alpha=0.1)
previous_score=0
for alpha in np.arange(0,1,0.1):
  sub_clf = MultinomialNB(alpha=alpha)
  sub_clf.fit(X_train,y_train)
  y_pred = sub_clf.predict(X_test)
  score = metrics.accuracy_score(y_test,y_pred)
  if score>previous_score:
    classifier=sub_clf
  print("Alpha: {}, Score: {}".format(alpha,score))
  

/usr/local/lib/python3.7/dist-packages/sklearn/naive_bayes.py:557: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10
  % _ALPHA_MIN


Alpha: 0.0, Score: 0.8681835043897613
Alpha: 0.1, Score: 0.8713985408680599
Alpha: 0.2, Score: 0.8710275751205638
Alpha: 0.30000000000000004, Score: 0.8710275751205638
Alpha: 0.4, Score: 0.8702856436255719
Alpha: 0.5, Score: 0.8700383331272412
Alpha: 0.6000000000000001, Score: 0.8702856436255719
Alpha: 0.7000000000000001, Score: 0.8697910226289106
Alpha: 0.8, Score: 0.8695437121305799
Alpha: 0.9, Score: 0.869172746383084


In [25]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.84      0.90      0.87      4040
           1       0.90      0.83      0.86      4047

    accuracy                           0.87      8087
   macro avg       0.87      0.87      0.87      8087
weighted avg       0.87      0.87      0.87      8087



##Decision Tree

In [26]:
 #
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

In [27]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.7547916409051564


In [28]:
score = metrics.accuracy_score(y_test, y_pred)
print("accuracy:   %0.3f" % score)
cm = metrics.confusion_matrix(y_test, y_pred)

accuracy:   0.755


In [29]:
y_pred = clf.predict(X_test)# Evaluate our model
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.76      0.75      0.75      4040
           1       0.75      0.76      0.76      4047

    accuracy                           0.75      8087
   macro avg       0.75      0.75      0.75      8087
weighted avg       0.75      0.75      0.75      8087



## Random Forest Classifier

In [ ]:
from sklearn.ensemble import RandomForestClassifier
forest = RandomForestClassifier()

In [ ]:
import numpy as np
from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import RandomForestClassifier


In [ ]:
rf=RandomForestClassifier()
rf_randomcv=RandomForestClassifier()
rf_randomcv.fit(X_train,y_train)

RandomForestClassifier()

In [ ]:
from sklearn.metrics import accuracy_score
y_pred=rf_randomcv.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print("Accuracy Score {}".format(accuracy_score(y_test,y_pred)))
print("Classification report: {}".format(classification_report(y_test,y_pred)))

[[3579  461]
 [ 640 3407]]
Accuracy Score 0.8638555706689749
Classification report:               precision    recall  f1-score   support

           0       0.85      0.89      0.87      4040
           1       0.88      0.84      0.86      4047

    accuracy                           0.86      8087
   macro avg       0.86      0.86      0.86      8087
weighted avg       0.86      0.86      0.86      8087



In [16]:
## Divide the dataset into Train and Test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=0)

##Linear SVC

In [30]:
svc = LinearSVC()
svc.fit(X_train, y_train)
y_pred = svc.predict(X_test)
score = metrics.accuracy_score(y_test, y_pred)
print("accuracy:   %0.3f" % score)
cm = metrics.confusion_matrix(y_test, y_pred)


accuracy:   0.900


In [32]:
from sklearn.metrics import classification_report, confusion_matrix
y_pred = svc.predict(X_test)# Evaluate our model
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[3623  417]
 [ 394 3653]]
              precision    recall  f1-score   support

           0       0.90      0.90      0.90      4040
           1       0.90      0.90      0.90      4047

    accuracy                           0.90      8087
   macro avg       0.90      0.90      0.90      8087
weighted avg       0.90      0.90      0.90      8087



##ADABOOST

In [ ]:
import numpy as np
from sklearn.model_selection import StratifiedKFold
from sklearn.ensemble import AdaBoostClassifier
from sklearn.svm import SVC 


grid = dict()
grid['n_estimators'] = [10, 50, 100, 500]
grid['learning_rate'] = [0.0001, 0.001, 0.01, 0.1, 1.0]
grid['algorithm'] = ['SAMME', 'SAMME.R']

kfold = StratifiedKFold(n_splits=3,shuffle=True,random_state=0)
gridcv = GridSearchCV(estimator=AdaBoostClassifier(base_estimator=SVC(kernel='linear', gamma="auto")),
                    param_grid=grid,
                    refit='f1',
                    cv=kfold,
                    verbose=0
                    )
gridcv.fit(X_train, y_train)
y_pred = grid.predict(X_test)# Evaluate our model

In [37]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[3480  560]
 [ 489 3558]]
              precision    recall  f1-score   support

           0       0.88      0.86      0.87      4040
           1       0.86      0.88      0.87      4047

    accuracy                           0.87      8087
   macro avg       0.87      0.87      0.87      8087
weighted avg       0.87      0.87      0.87      8087



##XGBoost

In [ ]:

xgb = XGBClassifier(booster='gblinear')

X = XGBClassifier()
X.fit(X_train,y_train)

y_pred = X.predict(X_test)
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))


[[3376  664]
 [1075 2972]]
0.7849635217014962
              precision    recall  f1-score   support

           0       0.76      0.84      0.80      4040
           1       0.82      0.73      0.77      4047

    accuracy                           0.78      8087
   macro avg       0.79      0.79      0.78      8087
weighted avg       0.79      0.78      0.78      8087

